### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by pedropgusmao** [DidierRLopes/step-detection-ML#1]
Hello Didier, 
This is a nice project. May I ask how you collected the data? Does Nurvv offer a way to export sensor data?
Thanks

**Comment by DidierRLopes** [comment]
Hi @pedropgusmao,

Thank you. I was working at Nurvv at the time, so I had access to this data as this was used to develop some of the internal algorithms of the product. 

I know the team is in the process of making this export sensor data a reality, but I'm unsure whether it will be available to the public or only meant to be used for RnD.

Feel free to reach out to the team (grant@nurvv.com and youssif@nurvv.com) and discuss your use case and it may be that they can provide you with this data.

You can tell them that I pointed them towards you, we are still in contact.

Closing this ticket, but if you have any other question feel free to ask :)
